//
//  ProductListPresenter.swift
//  LMProject
//
//  Created TapashM on 29/06/18.
//  Copyright © 2018 ITC Infotech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListPresenter: ProductListPresenterProtocol, ProductListInteractorOutputProtocol {

    weak private var view: ProductListViewProtocol?
    var interactor: ProductListInteractorInputProtocol?
    private let router: ProductListWireframeProtocol

    init(interface: ProductListViewProtocol, interactor: ProductListInteractorInputProtocol?, router: ProductListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
