//
//  ProductListInteractor.swift
//  LMProject
//
//  Created TapashM on 29/06/18.
//  Copyright © 2018 ITC Infotech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListInteractor: ProductListInteractorInputProtocol {

    weak var presenter: ProductListInteractorOutputProtocol?
}
