//
//  ProductListProtocols.swift
//  LMProject
//
//  Created TapashM on 29/06/18.
//  Copyright © 2018 ITC Infotech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProductListWireframeProtocol: class {

}
//MARK: Presenter -
protocol ProductListPresenterProtocol: class {

    var interactor: ProductListInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ProductListInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ProductListInteractorInputProtocol: class {

    var presenter: ProductListInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ProductListViewProtocol: class {

    var presenter: ProductListPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}

protocol ProductListRemoteDataManagerInputProtocol: class {
    var remoteRequestHandler: ProductListRemoteDataManagerOutputProtocol? { get set }
    // INTERACTOR -> REMOTEDATAMANAGER
    func retrieveProductList()
}

protocol ProductListRemoteDataManagerOutputProtocol: class {
    // REMOTEDATAMANAGER -> INTERACTOR
    func onProductsRetrieved(_ products: [Product])
    func onError()
}

