//
//  ProductListRouter.swift
//  LMProject
//
//  Created TapashM on 29/06/18.
//  Copyright © 2018 ITC Infotech. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListRouter: ProductListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createProductListModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let storyboard = UIStoryboard(name: "ProductList", bundle: nil)
        if let view = storyboard.instantiateViewController(withIdentifier: "ProductListViewController") as? ProductListViewController {
            let interactor = ProductListInteractor()
            let router = ProductListRouter()
            let presenter = ProductListPresenter(interface: view, interactor: interactor, router: router)
            
            view.presenter = presenter
            interactor.presenter = presenter
            router.viewController = view
            
            return view
        }
        return UIViewController()
    }
}
